// Prepares the site's source assets once. The output is committed, so CI never runs this.
//
//  - Mascot poses: copied from the app's asset catalog (trimmed 768 px PNGs) into
//    src/assets/mascot as high-quality WebP. Astro then makes AVIF/WebP sizes at build time.
//  - Icons: favicon.ico, PNG icons and apple-touch-icon from the app icon.
//  - Fonts: copies only the WOFF2 subsets the site uses from @fontsource into public/fonts
//    and writes src/styles/fonts.css with their unicode-range, so a browser downloads a
//    subset only when the page has characters from it.
//
// Usage: npm run assets   (NARRA_APP_DIR=/path/to/Narra if the site isn't inside the app repo)
import { mkdir, readFile, writeFile, copyFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { createRequire } from "node:module";

const SITE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const APP = process.env.NARRA_APP_DIR ?? path.resolve(SITE, "..");
const CATALOG = path.join(APP, "Narra", "Assets.xcassets");

const MASCOTS = [
  "mascot_onboarding_add",
  "mascot_settings",
  "mascot_hud_peek",
  "mascot_gallery_welcome",
  "mascot_welcome",
  "mascot_support_hero",
  "mascot_no_results",
  "mascot_guide_peek",
  "mascot_guide_explain",
];

async function mascots() {
  const out = path.join(SITE, "src/assets/mascot");
  await mkdir(out, { recursive: true });
  for (const name of MASCOTS) {
    const src = path.join(CATALOG, "Mascot", `${name}.imageset`, `${name}.png`);
    const dest = path.join(out, `${name.replace("mascot_", "")}.webp`);
    await sharp(src).webp({ quality: 92, alphaQuality: 100, effort: 6 }).toFile(dest);
  }
  console.log(`mascots: ${MASCOTS.length}`);
}

function ico(pngs) {
  // ICO container holding PNG images (supported by every current browser).
  const header = Buffer.alloc(6 + 16 * pngs.length);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(pngs.length, 4);
  let offset = header.length;
  pngs.forEach(({ size, data }, i) => {
    const e = 6 + 16 * i;
    header.writeUInt8(size >= 256 ? 0 : size, e);
    header.writeUInt8(size >= 256 ? 0 : size, e + 1);
    header.writeUInt8(0, e + 2);
    header.writeUInt8(0, e + 3);
    header.writeUInt16LE(1, e + 4);
    header.writeUInt16LE(32, e + 6);
    header.writeUInt32LE(data.length, e + 8);
    header.writeUInt32LE(offset, e + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...pngs.map((p) => p.data)]);
}

async function icons() {
  const src = path.join(CATALOG, "AppIcon.appiconset", "AppIcon.png");
  const pub = path.join(SITE, "public");
  const png = (size) => sharp(src).resize(size, size).png({ compressionLevel: 9 }).toBuffer();
  await writeFile(path.join(pub, "apple-touch-icon.png"), await png(180));
  await writeFile(path.join(pub, "icon-192.png"), await png(192));
  await writeFile(path.join(pub, "icon-512.png"), await png(512));
  await writeFile(path.join(pub, "favicon.ico"), ico([{ size: 16, data: await png(16) }, { size: 32, data: await png(32) }, { size: 48, data: await png(48) }]));
  await sharp(src).resize(256, 256).webp({ quality: 90 }).toFile(path.join(SITE, "src/assets/brand/app-icon.webp"));
  console.log("icons: done");
}

// family, package folder, css files to read, subsets to keep
const FONTS = [
  { pkg: "@fontsource-variable/nunito", css: ["wght.css"], subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext", "vietnamese"] },
  { pkg: "@fontsource/cormorant-garamond", css: ["600.css"], subsets: ["latin", "latin-ext", "cyrillic", "cyrillic-ext", "vietnamese"] },
  { pkg: "@fontsource-variable/vazirmatn", css: ["wght.css"], subsets: ["arabic"] },
  { pkg: "@fontsource/amiri", css: ["700.css"], subsets: ["arabic"] },
];

function fallback(name, locals, webFont, localFont) {
  const req = createRequire(import.meta.url);
  const web = req(`@capsizecss/metrics/${webFont}`);
  const loc = req(`@capsizecss/metrics/${localFont}`);
  const adjust = web.xWidthAvg / web.unitsPerEm / (loc.xWidthAvg / loc.unitsPerEm);
  const pct = (v) => `${(v * 100).toFixed(2)}%`;
  return `@font-face{font-family:"${name}";src:${locals.map((l) => `local("${l}")`).join(",")};size-adjust:${pct(adjust)};ascent-override:${pct(web.ascent / web.unitsPerEm / adjust)};descent-override:${pct(Math.abs(web.descent) / web.unitsPerEm / adjust)};line-gap-override:${pct(web.lineGap / web.unitsPerEm / adjust)}}`;
}

async function fonts() {
  const outDir = path.join(SITE, "public/fonts");
  await mkdir(outDir, { recursive: true });
  const blocks = [
    "/* Generated by scripts/prepare-assets.mjs. Do not edit. */",
    "/* Nunito, Cormorant Garamond, Vazirmatn and Amiri: SIL Open Font License 1.1 (license texts in public/fonts/*-LICENSE.txt). */",
  ];
  for (const font of FONTS) {
    const base = path.join(SITE, "node_modules", font.pkg);
    for (const cssFile of font.css) {
      const css = await readFile(path.join(base, cssFile), "utf8");
      for (const block of css.match(/@font-face\s*{[^}]+}/g) ?? []) {
        const file = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)?.[1];
        if (!file) continue;
        // Exact subset match: "latin" must not pick up "latin-ext" files and so on.
        if (!font.subsets.some((s) => new RegExp(`-${s}-(wght|\\d)`).test(file))) continue;
        // Amiri: use the smaller subset from scripts/subset_amiri.py when it's there.
        const subsetFile = file.replace("-normal.woff2", "-subset.woff2");
        const useSubset = file.startsWith("amiri-") && existsSync(path.join(outDir, subsetFile));
        if (!useSubset) await copyFile(path.join(base, "files", file), path.join(outDir, file));
        const family = block.match(/font-family:\s*'([^']+)'/)[1];
        const style = block.match(/font-style:\s*(\w+)/)[1];
        const weight = block.match(/font-weight:\s*([\d ]+);/)[1].trim();
        const range = block.match(/unicode-range:\s*([^;]+);/)[1];
        blocks.push(
          `@font-face{font-family:"${family}";font-style:${style};font-weight:${weight};font-display:swap;src:url(/fonts/${useSubset ? subsetFile : file}) format("woff2");unicode-range:${range}}`,
        );
      }
    }
  }
  // Metric-matched fallbacks (from @capsizecss/metrics): while the web fonts load, text is set
  // in a local font scaled to the same size, so swapping in the real font doesn't move anything.
  blocks.push(
    fallback("Nunito Fallback", ["Arial", "Helvetica Neue", "Helvetica"], "nunito", "arial"),
    fallback("Cormorant Fallback", ["Georgia"], "cormorantGaramond", "georgia"),
  );
  await writeFile(path.join(SITE, "src/styles/fonts.css"), blocks.join("\n") + "\n");
  for (const font of FONTS) {
    const name = font.pkg.split("/")[1];
    await copyFile(path.join(SITE, "node_modules", font.pkg, "LICENSE"), path.join(outDir, `${name}-LICENSE.txt`));
  }
  const files = (await readdir(outDir)).filter((f) => f.endsWith(".woff2"));
  console.log(`fonts: ${files.length} files`);
}

if (!existsSync(CATALOG)) {
  console.error(`App asset catalog not found at ${CATALOG}. Set NARRA_APP_DIR.`);
  process.exit(1);
}
await mascots();
await icons();
await fonts();
